name: surprise_alarms
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/.env
